name: neural_cognitive_modeling
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - torch
    - torchvision
    - matplotlib
    - seaborn
    - scikit-learn
    - numpy
    - pandas
    - tqdm
    - umap-learn
