_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
                - 51
                - 55
                - 105
            "2":
                - 1
                - 41
                - 51
                - 55
                - 105
            "3":
                - 1
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
alpha:
    value: 0.1
batch_size:
    value: 64
beta:
    value: 0.01
epochs:
    value: 20
learning_rate:
    value: 0.001
learning_rule:
    value: LPL
model:
    value: EnhancedCNN
